### PR TITLE
fix(preview): invalidate managed version checks on file updates

### PR DESCRIPTION
**Pull request by ewen-poch**
## Problem

F03 (P2): an open managed preview keeps its first inspection when the same logical file changes. Updated metadata, session filesRevision, file notifications, deletion and project archival do not refresh the head, editable text or latest-download context. Backend head checks prevent direct overwrite, but the preview still offers an obsolete edit baseline. Refreshing inspection alone also leaves old preview leases and shared image caches active; losing text availability during editing can hide Cancel.

## Proposed change

- Invalidate inspection using existing file metadata, session revisions, project/source lifecycle and scoped `project-files:changed` notifications; reuse effect cleanup and a component-local refresh generation to reject responses immediately when a notification arrives.
- Preserve explicitly selected historical versions while refreshing the head. Parent metadata still invalidates inspection after a local historical selection.
- Keep confirmed navigation and draft controls while refreshing, but withhold write authority until inspection succeeds. Disable saving after deletion/archival.
- Preserve drafts when a managed path advances and retain their original source version and expected-head baseline.
- Bind diff results and errors to the current inspection key, cancel obsolete comparisons, and reject responses that race with a file notification. Keep confirmed navigation while the existing comparison loading state is shown.
- Bind rendered content to the confirmed immutable selection and remount its resource lifecycle when that selection advances. Reuse the existing managed-version item converter so its locator, metadata and version ID agree, and pass that same item to PDF context actions. This refreshes text, HTML and shared image caches while the workbench tab remains unpinned and PDF/image evidence refers to the displayed version.
- Keep Cancel available throughout edit mode, including successful refreshes that return no text; Save stays disabled without fresh write capability.
- Register the new hook consumer in the public session-store facade contract.

## Scope and non-goals

Renderer-only production changes. No database/schema/serialization changes, migrations, new enum values, IPC channels, global cache, polling, or automatic draft rebasing. Existing optional metadata remains optional; no historical-data migration or compatibility layer is needed. `basedOnVersionId` is retained only in the existing component-local edit baseline; the hook also accepts the existing parent item for invalidation.

## Acceptance criteria and validation

Reproduction mounted the real React hook with the real history hook and lifecycle stores, stubbing only the existing API transport. On unchanged production code, the original 17 hook cases ran twice: **15 failures and 2 passing explicit-refresh controls**. Failures matched the report: inspect called once instead of twice, v1/text v1 instead of v2, and stale canEdit. Two additional race cases failed before synchronous invalidation was added: an obsolete error/rejection arriving with a notification could exit diff mode before React committed. Three component cases also failed before the production fix; another exposed historical-selection metadata invalidation before the follow-up fix.

The independent review also identified stale comparison output after inspection refresh. Three new hook cases (notification, metadata and old error) failed on the pre-fix code in two consecutive runs; three additional obsolete diff success/error/rejection race cases also failed before the follow-up fix. All six pass after the fix. The CI consumer-contract failure was reproduced locally before updating its explicit public-consumer list.

The final review regressions mount the real PreviewFileSurface, content renderers and resource hooks, stubbing only transport and browser Blob URLs. Against the rebased pre-fix Surface, two consecutive runs produced **7 failures and 3 passing controls**: text/HTML/image previews stayed on v2 after the head became v3, and an edit with unavailable text lost its controls. Historical content/leases and the text-available control remained valid. All pass after the fix; the checks also require exact-version resource acquisition and an unchanged, unpinned workbench item.

Four additional public behavior regressions cover PDF reading-context links and real image annotation creation for both upload and artifact sources after a head-only notification. On unchanged production code, they failed in two consecutive runs: upload evidence kept v2, artifact PDF linking was unavailable, and artifact image annotation creation was rejected. All four pass with matching v3 immutable locators.

At maintainer request, the branch was rebased onto main `1cccf098`. Conflicts with #2201 were resolved by preserving its inspect diagnostics and pending-save operation identity together with this PR's synchronous invalidation and original draft baseline. Both success and failure responses retain the generation guard; save retries compare and send the draft's original `basedOnVersionId`. Both sets of regression tests remain present. Main #2211 supplies the lifecycle fixture repair; this PR adds no lifecycle file change.

The maintainer approved the additional change to `e2e/accessibility.spec.ts`. CI and a prior complete local accessibility scan reported premature Settings focus-restoration failure, while normal retrying focus assertions passed twice. The unfixed complete rerun subsequently passed, confirming the timing-dependent nature of the diagnostic. Collection mode now uses the existing keyboard-outcome helper and retrying `toBeFocused()` assertion, with the same timeout and failure condition. Settings production behavior is unchanged.

Final checks ran after the last material edit:

| Behavior | Command | Result |
| --- | --- | --- |
| Hook freshness, historical selection, lifecycle, notification filtering/cleanup, failed refreshes, interleaved responses; preview draft/edit/download consumers; panel, item conversion, file index, IPC notifications, real text/HTML/image content and lease behavior, public session-store consumer contracts, PDF reading-context actions, real image annotation creation and lifecycle fixture/quit contracts; upstream save replay and accessibility reporter/runner contracts | Focused command below | 808 passed |
| Project Files owners, preview contract, file index, workspace and tool-preview consumers | `npm run test:module -- project_files_view` | 281 passed (overlaps focused set) |
| Main-process and sandbox types, including the CI-failing fixture | `npm run typecheck:node` | Passed |
| Renderer types | `npm run typecheck:web` | Passed |
| Repository lint | `npm run lint` | Passed |
| Patch whitespace | `git diff --check` | Passed |
| Electron build | `npm run build:e2e` | Passed |
| Accessibility quality signal, including deferred Settings focus restoration | `npm run test:e2e:accessibility:signal` | 11 tests, 21 scans, zero findings |
| Real Electron file previews: upload edits, version/diff navigation, images and PDF reading context | `npm run test:e2e -- e2e/workspace-files.spec.ts` | 10 passed on macOS |

```sh
npm test -- \
  src/main/delegation/production-composition.test.ts \
  src/main/app-lifecycle.test.ts \
  src/main/managed-file-versions/service.integration.test.ts \
  src/renderer/src/pages/workspace/useManagedVersionWorkflow.test.tsx \
  src/renderer/src/pages/workspace/PreviewFileSurface.test.tsx \
  src/renderer/src/pages/workspace/PreviewFileSurface.freshness.test.tsx \
  src/renderer/src/pages/workspace/PreviewPanel.test.tsx \
  src/renderer/src/pages/workspace/preview-file-item.test.ts \
  src/renderer/src/pages/workspace/use-project-files-index.test.tsx \
  src/main/managed-file-versions/ipc.test.ts \
  src/renderer/src/stores/session-store.test.ts \
  src/renderer/src/pages/workspace/previews/PreviewFileContent.test.tsx \
  src/renderer/src/pages/workspace/previews/useManagedPreviewResource.test.tsx \
  src/renderer/src/pages/workspace/previews/usePreviewFileContent.test.tsx \
  src/renderer/src/pages/workspace/previews/preview-file-reader.test.ts \
  src/renderer/src/pages/workspace/previews/renderers/ImagePreview.test.tsx \
  src/renderer/src/pages/workspace/annotations/image-annotation-source.test.ts \
  src/renderer/src/pages/workspace/annotations/ImagePointAnnotationSurface.test.tsx \
  scripts/ci/accessibility-reporter.test.ts \
  scripts/ci/run-accessibility-e2e.test.ts --maxWorkers=4
```

The affected-test explain command selects the full fallback because PreviewFileSurface is not a declared module owner. Per maintainer instruction, local validation uses the explicit module/consumer set above; PR CI is authoritative for the full plan. There are no disk-path operations, persisted-format changes, native IPC changes or Agent-framework-specific changes, so no local migration or cross-platform packaging lane was added. The prior macOS message-revision E2E failure passed in the subsequent CI run. The new PR CI run remains authoritative for the rebased head. Lifecycle composition tests and Electron E2E run outside the agent sandbox for local RPC listeners and Electron launch. The previous CI also reported macOS workspace-file resource-loading flakes and a Windows message-layout assertion; the affected macOS workspace-file suite passes locally, while the new CI remains authoritative for platform results.

## Review focus

Check consistent immutable locators for content, PDF context and image annotations without pinning the tab, retained Cancel after text becomes unavailable, diff result/error freshness, notification scope/cleanup, preservation of the original draft baseline, and parent metadata updates while a historical selection is pinned. The automated cases exercise the public renderer/event boundary; they do not claim a live second-window or Agent end-to-end run. The archival case deliberately keeps the preview mounted; normal global lifecycle navigation may already close it. AI review for the conflict-resolved head `5c969528` completed as **mergeable / no actionable findings** ([review](https://github.com/aipoch/open-science/pull/2198#issuecomment-5552074089)). Static checks pass on this head. Other CI lanes are still running; there are currently no failed checks. The PR remains unmerged.

### CODE REVIEW

**Comment by ewen-poch** [comment]
Addressed the version-identity mismatch in `PreviewFileSurface`. The confirmed version now goes through the existing managed-version item converter, which keeps its immutable locator, metadata and selected version together. PDF context actions receive that same item, so PDF links and image annotations refer to the version actually displayed. Default tabs remain unpinned and historical selections remain intact.

Added four public-behavior regressions for upload/artifact PDF linking and image annotation creation after a head-only update. All four failed in two consecutive runs before the fix, with the reported stale-version or rejected-action behavior, and pass after it. Final focused validation passes: 551 tests, the 269-test Project Files module, both runtime typechecks, lint, the Electron build and all 10 workspace-files E2E cases on macOS.

Rebased onto `2a4b12e3` without conflicts. The previous main-process typecheck failure is also gone after the rebase. This change stays within the existing PR files and adds no architecture, model, interaction, enum or persistence changes.

**Comment by ewen-poch** [comment]
The AI review for `157d1ace` completed with **mergeable / no actionable findings**.

The current Static checks failure is separate: CI tests merge commit `157daa65` against main `51a20156`. Main PR #2208 removed `holdSettingsInstallAdmission` and `getActiveSettingsInstallId` from the lifecycle fixture in `src/main/delegation/production-composition.test.ts`; the merged tree therefore fails TS2345 at line 953. Both dependencies are present on this branch and its local node typecheck passes.

Restoring the two existing fixture stubs would address this failure without changing production behavior, architecture, models or persistence. This file is outside the PR's existing change scope, so I have paused for maintainer approval before including that fix. Other CI lanes are still running; the PR remains unmerged.

**Comment by ewen-poch** [comment]
Main PR #2211 already restored the two required lifecycle fixture dependencies, so I rebased onto `263be550` and reused that repair. No duplicate fixture change is needed in this PR. The five preview commits are unchanged according to `git range-diff`, and the rebase had no conflicts.

The previous portable shard 3 report confirms seven failures in the same lifecycle fixture (`getActiveSettingsInstallId is not a function`). After the rebase, all 690 focused preview/lifecycle tests, the 269-test Project Files module, Node/Web typechecks, lint, the Electron build and all 10 workspace-files E2E cases pass locally.

The prior AI review was mergeable with no actionable findings; a new review will cover the rebased head. The previous Windows E2E shard 1 also recorded a 20 px bottom-follow overshoot in `message-tool-layout-stability.spec.ts` and passed on retry. That separate message-layout test is unchanged; the new CI will determine its current status.

**Comment by ewen-poch** [comment]
The AI review for `3d4b7ed2` completed with **mergeable / no actionable findings**. Static checks and all portable shards now pass; both Windows E2E shards pass as well. The remaining completed failure is the macOS accessibility quality signal.

Its artifact reports one finding: closing Settings did not restore focus to the Settings trigger. All 11 accessibility tests completed, all 21 axe scans are clean, and the 31 macOS workspace E2E cases pass. I reproduced the same diagnostic locally. The identical keyboard journey in normal assertion mode passed twice consecutively.

The collection-mode branch in `e2e/accessibility.spec.ts` samples `document.activeElement` immediately after the dialog becomes hidden, before reaching the existing retrying `toBeFocused()` assertion. Settings already restores focus in `onCloseAutoFocus`. The observed results point to a timing-sensitive diagnostic. The proposed bounded fix is to reuse the existing assertion helper to wait for focus restoration in collection mode too, retaining the failure condition and timeout.

That test file is outside this PR's current scope, so I have paused for maintainer approval before editing it. No Settings production, architecture, model, interaction, state-enum or persistence change is proposed. The PR remains unmerged.

**Comment by ewen-poch** [comment]
Rebased onto `1cccf098` and resolved the conflicts with #2201. The merged implementation retains inspect diagnostics, synchronous stale-response rejection and save operation replay. Save requests and replay matching use the original draft baseline, so an external head refresh does not silently change a pending save. Both branches' regression tests are retained and pass.

Also addressed the approved macOS accessibility diagnostic in `e2e/accessibility.spec.ts`: collection mode now uses the existing keyboard-outcome helper with the retrying `toBeFocused()` assertion. It retains the same timeout and failure condition. CI and a prior full local scan reproduced the false finding; a subsequent unfixed rerun passed, so this was an intermittent timing issue rather than a deterministic failure. The corrected complete signal passes all 11 tests and 21 scans with zero findings.

Final validation after the changes: 808 focused tests, the 281-test Project Files module, Node/Web typechecks, lint, the Electron build and all 10 workspace-files E2E cases pass. The change adds no Settings production behavior, architecture, data model, state enum or persistence changes. Fresh AI review and CI will cover this head.
