### PR TITLE
fix(notebook): honor reused cell languages and preserve run inputs

### PR DESCRIPTION
**Pull request by ewen-poch**
## Problem

Reusing a completed Python cell ID with `language: r` replaces its code but silently retains Python. The executor receives `{ language: "python", code: "x <- 42" }`, and the Run records the wrong `kernelKind`. R → Python has the same defect (N03).

## Change

An idle cell adopts an explicitly supplied language on each new write. If language is omitted, an existing cell keeps its language; only a new cell defaults to Python. Cell state, executor requests, and Run history agree.

The branch is rebased onto `main` at `b5077745`. N01 execution snapshots, busy-cell protection, and write cancellation are upstream. The N03 production change adds no persisted fields, schema migrations, dependencies, or renderer changes.

The approved CI follow-up also updates Compute and Electron tests/fixtures: await the existing survivor-job update notification instead of imposing a 500 ms polling deadline; preserve upstream's retrying focus assertion and exercise a delayed focus return; route restart shutdown through bounded cleanup while requiring a graceful close for persistence assertions. Forced cleanup reaps a blocked process and reports failure rather than claiming a successful save.

## Validation

The explicit-language regressions failed before the original fix, and the omitted-language cases reproduced the subsequent review finding before its fix. Tests cover Python → R, R → Python, omitted language on an existing R cell, queued-cell write rejection, executor inputs, returned state, and Run history.

The regressions use public runtime write/run/state boundaries and the existing injected executor. A queue spy observes admission without replacing behavior; no production test seam was added. Real Python/R interpreter processes are not exercised by these regressions.

Post-rebase validation: **534 tests passed across 11 files**, covering Notebook runtime, aggregate, queued inputs, architecture, workflows, IPC/RPC, application commands, delegation composition and app startup. Full Node/sandbox/Web typechecks and the changed files’ ESLint and Prettier checks passed.

## Review focus

Confirm that explicitly supplied language is honored, omission preserves an existing cell’s language, and the upstream busy-cell restriction prevents changes to already-submitted execution inputs or historical Runs.

Latest validation after rebase: 341 tests across six affected files; full Node/sandbox/Web typechecks; ESLint, Prettier and diff checks; Electron build; the full accessibility gate (11 tests, 21 axe scans, zero findings); and two consecutive message-revision restart E2E runs. The slow-poll and blocked-restart regressions failed before their fixes. Before the upstream focus fix, the delayed-focus case reproduced the exact CI finding in a complete 11-test/21-scan run; it now passes. Windows bottom-follow overshoot was not reproduced in three unchanged local runs; both Windows E2E shards passed in CI.

Final CI: [PR Gate run 33969429407](https://github.com/aipoch/open-science/actions/runs/33969429407) passed for `1b378a79`, including Static checks, all Ubuntu shards, coverage, Linux Notebook isolation, Windows core/E2E, macOS, and CodeQL. The first macOS attempt had an unrelated file-preview resource-error flake; its single rerun passed all 31 workspace tests with no flaky outcomes. Its root cause remains unconfirmed, and no error suppression was added.

### CODE REVIEW

**Comment by ewen-poch** [comment]
The omitted-language finding is valid. Two added local runtime regressions reproduce an existing R cell being dispatched to Python when the next write omits `language`; the four explicit-language cases still pass. The proposed behavior is: explicit language changes are honored, omitted language preserves an existing cell's language, and only a new cell defaults to Python. Implementing this requires passing the optional language through `runtime-service.ts` and applying the default inside the aggregate. That additional file is outside the currently approved PR scope, so the production fix is paused pending maintainer approval.

The CI failures have a separate, confirmed cause. Static checks report a missing `holdSettingsInstallAdmission` / `getActiveSettingsInstallId` dependency in `src/main/delegation/production-composition.test.ts`. The failed Ubuntu shard's blob report contains seven failures from that same fixture (`deps.getActiveSettingsInstallId is not a function`); those seven failures reproduce locally. The proposed CI fix supplies the two existing lifecycle dependencies in the test fixture, without changing application lifecycle behavior or CI configuration. This test file also requires scope approval. The module-test summary and final gate failures are downstream of these failures.

No architecture, persisted state, data relationships, or UI changes are proposed. Production changes have not been applied or pushed while scope approval is pending.

**Comment by ewen-poch** [comment]
Fixed the omitted-language regression in e45acda. The runtime now passes the optional language through unchanged: existing cells preserve their language when omitted, explicit Python/R changes are honored, and new cells still default to Python. The two previously failing omitted-language regressions now pass, including the queued-run case, alongside the explicit-language and immutable-input cases.

Fixed the CI lifecycle fixture in 6111dd6 by supplying `holdSettingsInstallAdmission` and `getActiveSettingsInstallId`. The seven failures from the Ubuntu shard now pass locally, and `npm run typecheck:node` succeeds. No application lifecycle behavior or CI configuration was changed.

Validation after the final edits: 447 tests passed across the 10 affected runtime, adapter, and delegation test files; `npm run typecheck:node` and `npm run lint` both passed. The PR description now reflects the complete language rules, the CI fixture fix, and current evidence.

**Comment by ewen-poch** [comment]
The updated static-check failure is a merge-integration issue, not the previous missing-dependency error. The latest `main` already declares `holdSettingsInstallAdmission` and `getActiveSettingsInstallId` twice in both the startup and delegated-work test fixtures. This PR's earlier fixture repair adds a third copy in the CI merge tree. CI reports TS1117 for these duplicate object properties.

I compared `main` and the exact PR merge ref. The proposed repair is to synchronize the branch with `main` and retain exactly one identical dependency pair in each fixture. This only removes duplicate test properties; it does not change application behavior, architecture, persisted data, or UI.

`src/main/app-startup.test.ts` is outside the currently approved file scope, so this integration repair is paused pending maintainer approval. The language fix and the previously missing dependencies have already been pushed, with 447 related tests, Node typechecks, and lint passing on the branch before these parallel base changes.

**Comment by ewen-poch** [comment]
Synchronized this branch with `main` in `8e42610`. The startup and delegation fixtures now retain one settings-lifecycle dependency pair each, resolving TS1117 in the CI merge tree. Both fixture files match `main`; this PR still changes only five Notebook files.

The merge preserves the new write-cancellation handling alongside this PR’s execution snapshots and explicit/omitted-language behavior. No additional state, persistence, data model, architecture, or UI changes were introduced by the integration repair.

Validation: 544 tests across 12 files passed, including the artifact write concurrency test that hit its one-second deadline on Ubuntu. Node/sandbox typechecks, lint, and the Electron E2E build passed. The message revision navigation/relaunch E2E also passed locally on macOS with the synchronization checks already added upstream; Windows confirmation is pending the new CI run.

The previous AI review was mergeable with no actionable findings. I am checking the new head’s review and the previously failing CI jobs.

**Comment by ewen-poch** [comment]
The static failure came from CI merge commit `26c16d8c`, which included `main` at `8865d540`. I checked out that exact commit and reproduced TS1117 at delegation fixture lines 962 and 970. Removing only the duplicated properties made the existing Node/sandbox typechecks pass. Later upstream commits have already corrected and then removed those obsolete Settings lifecycle fixture dependencies.

A read-only merge preview against `main` at `51a20156` exposed another integration issue: N01 now exists on both branches, but `cellExecutions` was declared on opposite sides of the cancellation-cleanup field. Git combined both declarations. The smallest branch repair moves the existing declaration to the same position as upstream. It adds no state or behavior and changes only `session-aggregate.ts`.

I also reproduced TS2300 from the uncorrected aggregate merge and verified the corrected merge with the existing typecheck. This validates the actual merge behavior in addition to checking the branch alone.

The Windows failures are separate: shard 1 failed during the Node header download with an Undici parser assertion, before tests started; shard 2 timed out during application startup before the Spanish settings test ran, then passed its built-in retry and was correctly rejected by `--fail-on-flaky-tests`. The installation failure was rerun. The new commit will rerun both Windows shards with unchanged assertions, timeouts and CI policy.

Implemented in `b6dd368`. Local validation: 291 Notebook tests passed; the delegation suite passed all 62 tests on a standalone retry after an `ENOTEMPTY` temporary-directory cleanup failure in the combined run. Branch and corrected-merge Node/sandbox typechecks, ESLint and formatting passed. No whole-branch merge was performed.

**Comment by ewen-poch** [comment]
The new static-check log exposed a second upstream fixture defect: the Settings lifecycle properties were removed from the fixture in `main` at `51a20156`, but `AppLifecycleDeps` still requires both. My earlier description of them as obsolete was incorrect.

I reproduced the exact TS2345 missing-property error, then moved the existing two defaults to the start of this PR’s fixture object so the three-way merge retains one copy of each. Only `production-composition.test.ts` changed. Both the branch and corrected merge passed Node/sandbox typechecks; all 62 delegation tests, ESLint and formatting passed. No production interface or behavior changed.

The `cellExecutions` duplicate declaration is fixed. The latest AI review of `b6dd3689` was mergeable with no actionable findings. Windows core encountered an Electron download `ECONNRESET` before tests started; the fresh CI run will retry installation with unchanged validation policy.

**Comment by ewen-poch** [comment]
Rebased onto current `main` (`263be550`) as requested. The branch now contains only the two N03 commits (`4423d6c0`, `63f53848`) and changes three Notebook files.

Dropped the N01 prerequisite and lifecycle fixture repairs already implemented upstream. Conflict resolution preserves main’s write cancellation and queue protection while retaining explicit-language updates and omitted-language preservation. No additional architecture, state, persistence or UI changes were introduced.

Post-rebase validation passed: 534 tests across 11 files; full Node/sandbox/Web typechecks; ESLint and Prettier for the changed files. Updated the branch with an explicit force-with-lease against the previously reviewed head.

**Comment by ewen-poch** [comment]
The rebased head `63f53848` passes Static checks, Windows core, Linux Notebook isolation, Ubuntu shards 2/3 and 3/3, and Windows E2E shard 2/2. The remaining failures in run `33966532660` are outside the three Notebook files in this PR:

- Ubuntu shard 1: `job-deletion-runtime-isolation.test.ts:21` timed out waiting for the survivor job to become successful. The test has a 500 ms polling deadline. The unchanged two-case suite passes locally; a timing issue is plausible but not yet a confirmed production defect.
- macOS: the accessibility report completed all 11 tests and 21 axe scans with zero axe violations, but recorded a keyboard finding: closing Settings did not restore focus to its trigger. Collection mode takes an immediate focus snapshot, whereas ordinary mode uses a retrying assertion. Three unchanged local collection-mode runs did not reproduce that finding; the third instead reported a teardown-time missing `reviewer:get-for-session` IPC handler.
- Windows E2E shard 1: the paced tool-turn layout test measured a 20 px return movement against a 2 px limit; message revision E2E also exceeded the 120-second app teardown deadline. Both passed their built-in retry, so `--fail-on-flaky-tests` correctly rejected the job.

No additional code has been changed. Addressing these findings may require Compute test/fixture or E2E test/fixture changes outside the approved Notebook scope, and the requested review-iteration limit has been reached. Further edits are paused for maintainer scope confirmation; the evidence does not justify weakening assertions or changing product interaction without reproduction.

**Comment by ewen-poch** [comment]
Rebased onto `main` at `b5077745` and pushed `1b378a7`.

- Compute deletion isolation now waits for the existing job-update callback instead of a 500 ms wall-clock deadline. A 750 ms repository delay reproduced the original `running` versus `success` failure before the fix; all five isolation/drain cases now pass.
- The upstream accessibility focus fix is preserved, with a delayed-focus regression. Before the fix, the complete gate finished all 11 tests and 21 axe scans but reported the same focus-restoration finding as CI. After the fix, the complete gate passes with zero findings.
- Electron restarts now use bounded cleanup. If graceful shutdown hangs, the process is reaped and the test fails explicitly; forced termination is never accepted as successful persistence. The regression failed before the fix and passes afterward. The existing revision-persistence E2E passed twice consecutively.

Validation: 341 affected tests, full Node/sandbox/Web typechecks, changed-file ESLint and Prettier, diff checks, and Electron build passed. No production UI, schema, or data relationships changed in this CI follow-up. The Windows bottom-follow assertion is unchanged: its reported overshoot did not reproduce in three local runs, so the new Windows CI result is still needed.

**Comment by ewen-poch** [comment]
The delayed-poll finding is not reproducible. The harness-owned `pollerRepository.findNonTerminal()` delegates to `jobRepository.findNonTerminal()` (test support, lines 212–215), and that original repository inherits `ComputeJobRepository.prototype.findNonTerminal`. The wrapper does not bypass the prototype spy.

I verified this dynamically by temporarily asserting `expect(delayedPoll).toHaveBeenCalledOnce()` after the survivor update: all three isolation cases passed, including the 750 ms case. Before replacing the old 500 ms wait, that same delayed case failed with survivor status `running` instead of `success`, matching the reported CI failure. The temporary diagnostic assertion was removed afterward; no source change is needed for this finding. Adding a new harness delay option or exposing its repository would add a test seam without correcting any observed defect.

**Comment by ewen-poch** [comment]
For `1b378a79`, Static checks, all three Ubuntu shards, Module tests and coverage, Linux Notebook isolation, Windows core, and both Windows E2E shards passed. macOS accessibility also passed.

The final gate caught a different macOS workspace flake: `workspace-files.spec.ts` / “shows structured text replacements with character-level highlights” emitted `Failed to load resource: net::ERR_FAILED`; all UI assertions passed and the built-in retry passed. The strict flaky-test gate correctly rejected the job. Three local repetitions with temporary resource diagnostics passed; they showed preview requests canceled with `ERR_ABORTED`, without the reported console failure. The CI trace contains no failed-resource URL, so this is not yet a confirmed root cause.

The temporary diagnostics were removed, and no renderer error allowlist or assertion threshold was changed. I am rerunning the failed macOS task once to check recurrence; this rerun is verification, not a claim that the new resource error has been fixed.

**Comment by ewen-poch** [comment]
CI is green for `1b378a799b49df3fa4391926809ebe30cc522f51`: [PR Gate run 33969429407](https://github.com/aipoch/open-science/actions/runs/33969429407) completed successfully. Static checks, all three Ubuntu shards, coverage, Linux Notebook isolation, Windows core, both Windows E2E shards, macOS, and CodeQL passed.

The single macOS rerun passed 19 functional journeys, all 31 workspace tests, 11 accessibility tests, and 3 visual tests, with no flaky outcomes. The first attempt's file-preview `ERR_FAILED` remains an unconfirmed intermittent issue; the rerun is not a root-cause fix, and no errors were suppressed. The AI review's delayed-poll concern was checked dynamically and answered above with the delegation path and passing spy assertion.
